In [23]:
import torch
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device=device,requires_grad=True)
print(my_tensor.dtype)

torch.float32


In [24]:
print(my_tensor)
print(my_tensor.shape)
print(my_tensor.requires_grad)
x=torch.empty(size=(2,3))
x=torch.zeros((3,3))
x=torch.randn((3,3))
# x=torch.eye((3,3))
# x=torch.linspace(start=0.1,end=1,step=10) ## it will have 10 values
# x=torch.empty(size=(1,5)).normal(mean=0,std=1)
x=torch.diag(torch.ones(3))
## converting tensors to other types
tensor=torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())


tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
torch.Size([2, 3])
True
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)


In [25]:
## Array to tensor conversion and vice versa

In [26]:
import numpy as np
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)
np_array_back=tensor.numpy()
np_array_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
import torch
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
z1=torch.empty(3)
t=torch.add(x,y,out=z1)
t=t+x
print(t)

tensor([11., 12., 13.])


In [28]:
z1=torch.empty(3)
torch.add(x,y,out=z1)

tensor([10., 10., 10.])

In [29]:
z=torch.add(x,y)
z=x+y
z

tensor([10, 10, 10])

In [30]:
z2=torch.add(x,y)
z2=x+y
z2

tensor([10, 10, 10])

In [31]:
## exponentatioin

In [32]:
z=x.pow(2)
z

tensor([1, 4, 9])

In [33]:
z=x.pow(2)
z

tensor([1, 4, 9])

In [34]:
## Simple comparsion

In [35]:
z=x>0
print(z)

tensor([True, True, True])


In [36]:
z=x<0
print(z)

tensor([False, False, False])


In [37]:
## matrix multiplication

In [38]:
x1=torch.rand((2,5))
x=torch.rand((5,3))
x2=torch.rand(3,3)
x3=torch.mm(x1,x)
x3=x1.mm(x)
x3

tensor([[1.5605, 1.0609, 1.4386],
        [0.8612, 0.4286, 0.7490]])

In [39]:
## matrix exponentation

In [40]:
matrix_expo=torch.rand(5,5)
print(matrix_expo)
print(matrix_expo.matrix_power(3))

tensor([[0.8387, 0.5016, 0.3348, 0.2496, 0.2596],
        [0.9293, 0.4777, 0.0418, 0.6805, 0.5967],
        [0.1483, 0.7720, 0.1188, 0.0452, 0.0540],
        [0.9501, 0.9785, 0.1435, 0.6971, 0.8636],
        [0.9208, 0.5552, 0.5266, 0.3697, 0.7113]])
tensor([[4.3681, 3.2090, 1.2958, 2.2645, 2.6350],
        [6.3569, 4.7000, 1.9641, 3.2561, 3.8774],
        [2.5092, 1.7994, 0.7556, 1.3054, 1.5673],
        [8.3899, 6.1939, 2.5975, 4.3005, 5.1420],
        [6.2742, 4.6457, 1.8861, 3.2455, 3.7962]])


In [41]:
torch.matrix_exp(matrix_expo)

tensor([[4.3069, 2.3476, 1.0788, 1.5050, 1.7097],
        [4.5038, 4.0836, 1.1392, 2.5211, 2.8056],
        [1.5565, 1.7557, 1.4674, 0.8367, 0.9198],
        [5.6612, 4.3882, 1.5654, 4.1573, 3.7948],
        [4.4381, 3.2218, 1.6420, 2.1494, 3.8385]])

In [42]:
matrix_expo.matrix_power(3)


tensor([[4.3681, 3.2090, 1.2958, 2.2645, 2.6350],
        [6.3569, 4.7000, 1.9641, 3.2561, 3.8774],
        [2.5092, 1.7994, 0.7556, 1.3054, 1.5673],
        [8.3899, 6.1939, 2.5975, 4.3005, 5.1420],
        [6.2742, 4.6457, 1.8861, 3.2455, 3.7962]])

In [43]:
## element wise mult

In [77]:
# z=torch.dot(x,y)
# print(z)

In [ ]:
## batch matrix multiplication

In [45]:
batch=32
n=10
m=20
p=30
tensor1=torch.randn((batch,n,m))
tensor1

tensor([[[ 1.4262, -0.0878,  0.3358,  ..., -1.7386, -0.1177, -1.8704],
         [-0.6868, -1.3015, -1.7572,  ..., -0.1168, -0.5959, -0.2452],
         [ 1.2355,  1.2589, -1.3399,  ..., -1.5731,  0.0188, -0.1464],
         ...,
         [ 1.0111, -0.4833,  0.9695,  ..., -0.2995,  1.1992, -1.2961],
         [ 1.7048, -1.2583, -1.1777,  ..., -0.2523, -0.2838,  1.7275],
         [ 2.0491,  0.3591,  0.5070,  ..., -0.1456, -0.2150, -0.9697]],

        [[ 0.8888, -1.0564,  0.5157,  ..., -0.7551, -0.3911, -0.4300],
         [-0.7718, -0.0824, -0.7117,  ..., -0.6548, -2.3780,  0.6925],
         [ 0.1571, -0.4180, -0.6266,  ..., -0.8607,  1.6041, -0.4082],
         ...,
         [ 0.3266, -0.9213, -1.5340,  ..., -1.1714,  0.0649, -1.7951],
         [-1.2065, -0.4344,  0.5502,  ..., -0.0098, -2.4618, -2.3853],
         [-0.6478,  0.8037,  0.9063,  ..., -0.0478,  0.6766,  0.6604]],

        [[-0.7948,  0.9713, -0.0418,  ..., -0.2763,  0.8705, -0.2645],
         [-1.8028,  0.2236,  1.8168,  ...,  2

In [ ]:
torch.bmm(tensor1,tensor1.transpose(1,2)) ##(batch,n,m,p)

In [ ]:
# examples of broadcasting

In [46]:
x1=torch.randn((5,5))
x2=torch.randn((1,5))
z=x1-x2
z_multiplication=x1**x2
z_multiplication

tensor([[   nan,    nan,    nan, 0.9709, 1.1315],
        [   nan,    nan, 0.9204, 1.0312, 0.2260],
        [   nan,    nan, 1.1046,    nan,    nan],
        [1.1664, 1.7129, 0.9447, 0.8822,    nan],
        [2.6182, 0.9813,    nan,    nan, 0.1340]])

In [ ]:
## other useful tensor operations

In [47]:
sum_x=torch.sum(x,dim=0)
values,indices=torch.max(x,dim=0)
values,indices=torch.min(x,dim=0)
abs_x=torch.abs(x)
z=torch.argmax(x,dim=0)
z=torch.argmin(x,dim=0)
print(z)

tensor([3, 2, 3])


In [ ]:
## other useful tensor operations

In [48]:
sum_x=torch.sum(x,dim=0)
values,indices=torch.max(x,dim=0)
values,indices=torch.min(x,dim=0)
abs_x=torch.abs(x)
print(abs_x)

tensor([[0.8492, 0.6314, 0.9738],
        [0.8869, 0.6603, 0.4167],
        [0.4561, 0.0427, 0.5487],
        [0.0437, 0.1062, 0.1639],
        [0.8229, 0.3561, 0.4957]])


In [49]:
z=torch.eq(x,y)
z

tensor([[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]])

In [51]:
sorted,y_indices=torch.sort(y,dim=0,descending=False)

In [50]:
z=torch.clamp(x,min=0)

In [ ]:
## Tensor Indexing

In [52]:
batch_size=25
features=25
x=torch.randn((batch_size,features))
print(x[0].shape)
print(x[:,0].shape)
print(x[2,0:10])

torch.Size([25])
torch.Size([25])
tensor([ 0.0102, -0.1571,  0.9267,  0.3432,  0.5442,  1.0034, -0.7957,  0.8512,
        -0.6988, -0.4610])


In [53]:
x[0,0]=100

In [54]:
x=torch.randn((3,5))
rows=torch.tensor([1,0])
cols=torch.tensor([4,0])
print(x[rows,cols])

tensor([ 1.0765, -0.2935])


In [ ]:
## More advanced indexing

In [55]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [56]:
print(x[x<2]^x[x>8])

tensor([9, 8])


In [57]:
print(x[x.remainder(2)==0])

tensor([0, 2, 4, 6, 8])


In [ ]:
## useful operations

In [58]:
print(torch.where(x>5,x,x**2))

tensor([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])


In [59]:
print(torch.tensor([0,0,0,1,1,2,3,4]).unique())
print(x.ndim)
print(x.numel)

tensor([0, 1, 2, 3, 4])
1
<built-in method numel of Tensor object at 0x7e734b112580>


In [ ]:
## tensor reshaping

In [60]:
import torch
x=torch.arange(9)
x_3x3=x.reshape(3,3)
y=x_3x3.t()
y
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [61]:
x1=torch.randn((2,2))
x2=torch.randn((3,3))

In [62]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [65]:
x1=torch.rand((2,5))
x2=torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [66]:
z=x1.view(-1)
print(z.shape)

torch.Size([10])


In [68]:
batch=64
x=torch.rand((batch,2,5))
z=x.view(batch,-1)
print(z.shape)
z=x.permute(0,2,1)

torch.Size([64, 10])


In [76]:
x=torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)
x=torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)
z=x.squeeze(1)
print(z.shape)


torch.Size([1, 10])
torch.Size([10, 1])
torch.Size([1, 1, 10])
torch.Size([1, 10])
